### ISSUE TITLE
different grays

### ISSUE THREAD

**Issue by Dubascudes** [Gunnthorian/BareBones#1]
I'm surprised your trained eye did not notice- your top banner is a different shade of gray than the logo background

**Comment by Gunnthorian** [comment]
what logo background? the logo’s background is transparent, are you referring to the top navigation bar and the trident logo? the trident logos’s background is blue

**Comment by Dubascudes** [comment]
i also left this on the wrong github rip
i mean the background of the page, sorry. its 55,55,55 vs 53,53,53

**Comment by Dubascudes** [comment]
no not page
idk actually. two containers at the top (header) have different grays

**Comment by Gunnthorian** [comment]
oh yeah you’re right i totally forgot 😂 i did that on purpose initially so that i could see the width of the inner one for testing but forgot to change it back
